using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Ozeki
{
    public enum OzAIModelSize
    {
        UNKNOWN,
        PCount14M,
        PCount17M,
        PCount22M,
        PCount33M,
        PCount60M,
        PCount70M,
        PCount80M,
        PCount109M,
        PCount137M,
        PCount160M,
        PCount220M,
        PCount250M,
        PCount270M,
        PCount335M,
        PCount410M,
        PCount450M,
        PCount770M,
        PCount780M,
        PCount0_5B,
        PCount1B,
        PCount1_3B,
        PCount1_4B,
        PCount2B,
        PCount2_8B,
        PCount3B,
        PCount4B,
        PCount6B,
        PCount6_9B,
        PCount7B,
        PCount8B,
        PCount9B,
        PCount11B,
        PCount12B,
        PCount13B,
        PCount14B,
        PCount15B,
        PCount16B,
        PCount20B,
        PCount30B,
        PCount34B,
        PCount35B,
        PCount40B,
        PCount65B,
        PCount70B,
        PCount236B,
        PCount314B,
        SMALL,
        MEDIUM,
        LARGE,
        XL,
        PCountA2_7B,
        PCount8x7B,
        PCount8x22B,
        PCount16x12B,
        PCount10B_128x3_66B,
        PCount57B_A14B,
        PCount27Bs
    }
}
